/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";

import * as THREE from "three";

export function Room(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/room.glb");
  const { actions } = useAnimations(animations, group);
  const texture = useTexture("textures/baked.jpg");
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Rug"
          castShadow
          receiveShadow
          geometry={nodes.Rug.geometry}
          material={textureMaterial}
          position={[-0.281, 0.009, 0.765]}
        />
        <group name="Plant" position={[-0.78, 1.071, -1.61]}>
          <mesh
            name="mesh24448074"
            castShadow
            receiveShadow
            geometry={nodes.mesh24448074.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh24448074_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh24448074_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh24448074_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh24448074_2.geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="Palm"
          position={[2.13, -0.081, -1.055]}
          rotation={[-Math.PI, 0.672, -Math.PI]}
        >
          <mesh
            name="palm_tree_01-Mesh"
            castShadow
            receiveShadow
            geometry={nodes["palm_tree_01-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="palm_tree_01-Mesh_1"
            castShadow
            receiveShadow
            geometry={nodes["palm_tree_01-Mesh_1"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="palm_tree_01-Mesh_2"
            castShadow
            receiveShadow
            geometry={nodes["palm_tree_01-Mesh_2"].geometry}
            material={textureMaterial}
          />
        </group>
        <group name="Plane">
          <mesh
            name="Plane001"
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_3.geometry}
            material={textureGlassMaterial}
          />
        </group>
        <group
          name="Guitar"
          position={[-2.05, 0.006, 1.631]}
          rotation={[-2.918, 1.463, 2.9]}
          scale={0.036}
        >
          <mesh
            name="Mesh59_Model_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh59_Model_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh59_Model_1_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh59_Model_1_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh59_Model_1_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh59_Model_1_4.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh59_Model_1_5.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="Skateboard_Mesh"
          castShadow
          receiveShadow
          geometry={nodes.Skateboard_Mesh.geometry}
          material={textureMaterial}
          position={[1.713, 0.416, -1.885]}
          rotation={[0.595, 1.502, -2.593]}
          scale={[0.131, 0.189, 0.157]}
        />
        <mesh
          name="Rubik_Cube"
          castShadow
          receiveShadow
          geometry={nodes.Rubik_Cube.geometry}
          material={textureMaterial}
          position={[-0.624, 2.082, -2.046]}
          rotation={[0, 1.283, 0]}
          scale={6.008}
        />
        <group
          name="Desk"
          position={[-0.074, 0, -1.521]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Plane001_Plane002_BlackWood002"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_Plane002_BlackWood002.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_Plane002_BlackWood002_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_Plane002_BlackWood002_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_Plane002_BlackWood002_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_4"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_Plane002_BlackWood002_4.geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="iMac"
          position={[0.454, 0.939, -1.723]}
          rotation={[Math.PI, -1.099, Math.PI]}
        >
          <mesh
            name="iMac_1001"
            castShadow
            receiveShadow
            geometry={nodes.iMac_1001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="iMac_1001_1"
            castShadow
            receiveShadow
            geometry={nodes.iMac_1001_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="iMac_1001_2"
            castShadow
            receiveShadow
            geometry={nodes.iMac_1001_2.geometry}
            material={textureMaterial}
          />
        </group>
        <group name="LavaLamp" position={[-1.302, 2.071, -1.986]}>
          <mesh
            name="Node-Mesh002"
            castShadow
            receiveShadow
            geometry={nodes["Node-Mesh002"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="Node-Mesh002_1"
            castShadow
            receiveShadow
            geometry={nodes["Node-Mesh002_1"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="Node-Mesh002_2"
            castShadow
            receiveShadow
            geometry={nodes["Node-Mesh002_2"].geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="Chair"
          position={[0.038, 0, -0.764]}
          rotation={[0, -0.35, 0]}
        >
          <mesh
            name="Node-Mesh001"
            castShadow
            receiveShadow
            geometry={nodes["Node-Mesh001"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="Node-Mesh001_1"
            castShadow
            receiveShadow
            geometry={nodes["Node-Mesh001_1"].geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="keyboard"
          position={[0.215, 0.948, -1.215]}
          rotation={[0, -0.224, 0]}
          scale={0.63}
        >
          <mesh
            name="mesh425587018001"
            castShadow
            receiveShadow
            geometry={nodes.mesh425587018001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh425587018001_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh425587018001_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh425587018001_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh425587018001_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh425587018001_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh425587018001_3.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="Comp_Mouse"
          castShadow
          receiveShadow
          geometry={nodes.Comp_Mouse.geometry}
          material={textureMaterial}
          position={[-0.008, 0, 0.076]}
        />
        <group name="SM_ShelfSM_Shelf1" position={[-0.868, 1.694, -2.038]}>
          <mesh
            name="SM_ShelfSM_Shelf1_1001"
            castShadow
            receiveShadow
            geometry={nodes.SM_ShelfSM_Shelf1_1001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="SM_ShelfSM_Shelf1_1001_1"
            castShadow
            receiveShadow
            geometry={nodes.SM_ShelfSM_Shelf1_1001_1.geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="Empty"
          position={[0.041, 0.368, -0.733]}
          rotation={[-Math.PI, 0.345, -Math.PI]}
        />
        <group
          name="RootNode"
          position={[-2.156, 0, 0]}
          rotation={[0.052, -0.838, 0.057]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/room.glb");
