/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/room.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";

import * as THREE from "three";

export function Room(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/room.glb");
  const { actions } = useAnimations(animations, group);
  const texture = useTexture("textures/baked.jpg");
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="RootNode"
          position={[-2.156, 0, 0]}
          rotation={[0.052, -0.838, 0.057]}
        />
        <group name="Shelf" position={[-0.868, 1.694, -2.038]}>
          <mesh
            name="SM_ShelfSM_Shelf1_1"
            geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="SM_ShelfSM_Shelf1_1_1"
            geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="Rug"
          geometry={nodes.Rug.geometry}
          material={textureMaterial}
          position={[-0.281, 0.009, 0.765]}
        />
        <group
          name="Keyboard"
          position={[-0.044, 0.981, -1.346]}
          rotation={[0, -0.165, 0]}
        >
          <mesh
            name="mesh425587018"
            geometry={nodes.mesh425587018.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh425587018_1"
            geometry={nodes.mesh425587018_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh425587018_2"
            geometry={nodes.mesh425587018_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh425587018_3"
            geometry={nodes.mesh425587018_3.geometry}
            material={textureMaterial}
          />
        </group>
        <group name="Plant" position={[-0.78, 1.071, -1.61]}>
          <mesh
            name="mesh24448074"
            geometry={nodes.mesh24448074.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh24448074_1"
            geometry={nodes.mesh24448074_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh24448074_2"
            geometry={nodes.mesh24448074_2.geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="Palm"
          position={[2.13, -0.081, -1.055]}
          rotation={[-Math.PI, 0.672, -Math.PI]}
        >
          <mesh
            name="palm_tree_01-Mesh"
            geometry={nodes["palm_tree_01-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="palm_tree_01-Mesh_1"
            geometry={nodes["palm_tree_01-Mesh_1"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="palm_tree_01-Mesh_2"
            geometry={nodes["palm_tree_01-Mesh_2"].geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="Chair"
          position={[-0.278, 0, -0.708]}
          rotation={[0, -0.376, 0]}
        >
          <mesh
            name="Node-Mesh"
            geometry={nodes["Node-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="Node-Mesh_1"
            geometry={nodes["Node-Mesh_1"].geometry}
            material={textureMaterial}
          />
        </group>
        <group name="Plane">
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_1"
            geometry={nodes.Plane001_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_2"
            geometry={nodes.Plane001_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_3"
            geometry={nodes.Plane001_3.geometry}
            material={textureGlassMaterial}
          />
        </group>
        <group
          name="Guitar"
          position={[-2.05, 0.006, 1.631]}
          rotation={[-2.918, 1.463, 2.9]}
          scale={0.036}
        >
          <mesh
            name="Mesh59_Model_1"
            geometry={nodes.Mesh59_Model_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_1"
            geometry={nodes.Mesh59_Model_1_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_2"
            geometry={nodes.Mesh59_Model_1_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_3"
            geometry={nodes.Mesh59_Model_1_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_4"
            geometry={nodes.Mesh59_Model_1_4.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Mesh59_Model_1_5"
            geometry={nodes.Mesh59_Model_1_5.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="Skateboard_Mesh"
          geometry={nodes.Skateboard_Mesh.geometry}
          material={textureMaterial}
          position={[1.713, 0.575, -1.796]}
          rotation={[0.595, 1.502, -2.593]}
          scale={[0.176, 0.254, 0.254]}
        />
        <mesh
          name="Rubik_Cube"
          geometry={nodes.Rubik_Cube.geometry}
          material={textureMaterial}
          position={[-0.624, 2.082, -2.046]}
          rotation={[0, 1.283, 0]}
          scale={6.008}
        />
        <group
          name="Desk"
          position={[-0.074, 0, -1.521]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Plane001_Plane002_BlackWood002"
            geometry={nodes.Plane001_Plane002_BlackWood002.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_1"
            geometry={nodes.Plane001_Plane002_BlackWood002_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_2"
            geometry={nodes.Plane001_Plane002_BlackWood002_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_3"
            geometry={nodes.Plane001_Plane002_BlackWood002_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_Plane002_BlackWood002_4"
            geometry={nodes.Plane001_Plane002_BlackWood002_4.geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="iMac"
          position={[0.454, 0.939, -1.723]}
          rotation={[Math.PI, -1.099, Math.PI]}
        >
          <mesh
            name="iMac_1001"
            geometry={nodes.iMac_1001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="iMac_1001_1"
            geometry={nodes.iMac_1001_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="iMac_1001_2"
            geometry={nodes.iMac_1001_2.geometry}
            material={textureMaterial}
          />
        </group>
        <group name="LavaLamp" position={[-1.302, 2.071, -1.986]}>
          <mesh
            name="Node-Mesh002"
            geometry={nodes["Node-Mesh002"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="Node-Mesh002_1"
            geometry={nodes["Node-Mesh002_1"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="Node-Mesh002_2"
            geometry={nodes["Node-Mesh002_2"].geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="Comp_Mouse"
          geometry={nodes.Comp_Mouse.geometry}
          material={textureMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/room.glb");
